# Generated by Django 3.2 on 2021-04-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='current_date',
        ),
    ]
